{{- if .Values.k8s.services.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: hbase-master
  labels:
    svc: hbase-master
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: ClusterIP
  ports:
    - name: master-api
      port: {{ .Values.apps.hbase.master.ports.api }}
      protocol: "TCP"
      targetPort: 16000
    - name: master-ui
      port: {{ .Values.apps.hbase.master.ports.ui }}
      protocol: "TCP"
      targetPort: 16010
    - name: rs-api
      port: {{ .Values.apps.hbase.regionserver.ports.api }}
      protocol: "TCP"
      targetPort: 16020
    - name: rs-ui
      port: {{ .Values.apps.hbase.regionserver.ports.ui }}
      protocol: "TCP"
      targetPort: 16030
    - name: zk-api
      port: {{ .Values.apps.hbase.master.ports.zk }}
      protocol: "TCP"
      targetPort: 2181
  selector:
    run: hbase-master
{{- if .Values.apps.kdc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: kdc
  labels:
    svc: kdc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: ClusterIP
  ports:
    - name: kdc-tcp
      port: {{ .Values.apps.kdc.ports.tcp }}
      protocol: "TCP"
      targetPort: 88
    - name: kdc-udp
      port: {{ .Values.apps.kdc.ports.udp }}
      protocol: "UDP"
      targetPort: 88
  selector:
    run: kdc
{{- end }}
{{- end }}