{{- if .Values.k8s.ingress.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: hbase-master-ui
  labels:
    component: ingress
    app: hbase
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
    - host: {{ .Values.k8s.ingress.hbase_master.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: hbase-master-ui
              servicePort: 16010
  tls:
    - hosts:
      - {{ .Values.k8s.ingress.hbase_master.host }}
{{- end }}