namespace: hbase
serviceAccountName: default

nodeports:
  hbase: 32700

images:
  hbase: localhost:5001/hbase-standalone:v0.1
  kdc: localhost:5001/kdc:v0.1

k8s:
  roles:
    enabled: false
  services:
    enabled: true
  ingress:
    enabled: false

apps:
  hbase:
    master:
      ports: 
        api: 16000
        ui: 16010
        zk: 2181
    regionserver:
      ports: 
        api: 16020
        ui: 16030
  kdc:
    enabled: true
    ports: 
      tcp: 88
      udp: 88

config:
  WITH_PHOENIX: "true"
  WITH_SECURITY: "false"
