namespace: hbase-example
serviceAccountName: default

nodeports:
  hbase: 32700

images:
  hbase: larsgeorge/hbase-standalone:2.4.15
  kdc: larsgeorge/kdc:1.0.0

k8s:
  roles:
    enabled: false
  services:
    enabled: true
    hbase_master:
      host: localhost
      ports: 
        api: 16000
        ui: 16010
    hbase_regionserver:
      host: localhost
      ports: 
        api: 16020
        ui: 16030
  ingress:
    enabled: false

kdc:
  enabled: false

config:
  VAR0: "0"
